### PR TITLE
Add new tests property to groupsData

### PR DESCRIPTION
**Pull request by andrewvasilchuk**
It would be great to add some testing frameworks like: `Jest`, `Cypress`, `Jasmine` etc.

### CODE REVIEW

**Comment by yoksel** [comment]
Good idea! Could you add some data?

**Comment by andrewvasilchuk** [comment]
@yoksel, sure, I will add ASAP.

**Comment by andrewvasilchuk** [comment]
@yoksel, Ready to merge 😊

**Comment by yoksel** [comment]
Thank you : )

**Pull request merged**
